title: ＃f
email: noppelabs@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  ＃f unofficial twitter client for iOS.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: noppefoxwolf
github_username:  noppefoxwolf

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude: ['vendor/bundle', 'node_modules', '.git', '.bundle', '.saas-cache', '.bowerrc', '.gitignore', 'Gemfile', 'Gemfile.lock']